CREATE TABLE IF NOT EXISTS greetings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);

INSERT INTO greetings (id, name)
VALUES (1, 'HELLO WORLD')
ON DUPLICATE KEY UPDATE name = 'HELLO WORLD';