apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rjm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/David88c/book-review-devops.git
    targetRevision: main
    path: k8s/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: rjm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
