# k8s/minikube/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rjm
resources:
  - namespace.yaml
  - app-config.yaml
  - mysql-svc.yaml
  - mysql-statefulset.yaml
  - backend-svc.yaml
  - backend-deploy.yaml
  - frontend-svc.yaml
  - frontend-deploy.yaml
  - ingress.yaml
images:
  - name: docker.io/david817/book-review-backend
    newTag: 0b3b021
  - name: docker.io/david817/book-review-frontend
    newTag: 0b3b021
